

class PlayerInputConsts:
    """ Various bitflags representing a set of keypress game inputs. """

    EMPTY = "BUILTIN_VOID_HARDWARE_INPUT"

    ABILITY_1 = "BUILTIN_KEYDOWN_HARDWARE_INPUT_ABILITY_1"
    ABILITY_2 = "BUILTIN_KEYDOWN_HARDWARE_INPUT_ABILITY_2"
    ABILITY_3 = "BUILTIN_KEYDOWN_HARDWARE_INPUT_ABILITY_3"
    ABILITY_4 = "BUILTIN_KEYDOWN_HARDWARE_INPUT_ABILITY_4"

    SWAP_TARGET = "BUILTIN_KEYDOWN_HARDWARE_INPUT_SWAP_TARGET_NEXT"

    START_MOVE_UP = "BUILTIN_KEYDOWN_HARDWARE_INPUT_MOVE_UP"
    STOP_MOVE_UP = "BUILTIN_KEYUP_HARDWARE_INPUT_MOVE_UP"
    START_MOVE_LEFT = "BUILTIN_KEYDOWN_HARDWARE_INPUT_MOVE_LEFT"
    STOP_MOVE_LEFT = "BUILTIN_KEYUP_HARDWARE_INPUT_MOVE_LEFT"
    START_MOVE_DOWN = "BUILTIN_KEYDOWN_HARDWARE_INPUT_MOVE_DOWN"
    STOP_MOVE_DOWN = "BUILTIN_KEYUP_HARDWARE_INPUT_MOVE_DOWN"
    START_MOVE_RIGHT = "BUILTIN_KEYDOWN_HARDWARE_INPUT_MOVE_UP"
    STOP_MOVE_RIGHT = "BUILTIN_KEYUP_HARDWARE_INPUT_MOVE_RIGHT"