

class HardwareInputConsts:

    KEYBOARD_KEYDOWN_1 = "BUILTIN_KEYBOARD_KEYDOWN_1"
    KEYBOARD_KEYDOWN_2 = "BUILTIN_KEYBOARD_KEYDOWN_2"
    KEYBOARD_KEYDOWN_3 = "BUILTIN_KEYBOARD_KEYDOWN_3"
    KEYBOARD_KEYDOWN_4 = "BUILTIN_KEYBOARD_KEYDOWN_4"

    KEYBOARD_KEYDOWN_TAB = "BUILTIN_KEYBOARD_KEYDOWN_TAB"

    KEYBOARD_KEYDOWN_ARROW_UP = "BUILTIN_KEYBOARD_KEYDOWN_ARROW_UP"
    KEYBOARD_KEYUP_ARROW_UP = "BUILTIN_KEYBOARD_KEYUP_ARROW_UP"

    KEYBOARD_KEYDOWN_ARROW_LEFT  = "BUILTIN_KEYBOARD_KEYDOWN_ARROW_LEFT"
    KEYBOARD_KEYUP_ARROW_LEFT  = "BUILTIN_KEYBOARD_KEYUP_ARROW_LEFT"

    KEYBOARD_KEYDOWN_ARROW_DOWN  = "BUILTIN_KEYBOARD_KEYDOWN_ARROW_DOWN"
    KEYBOARD_KEYUP_ARROW_DOWN  = "BUILTIN_KEYBOARD_KEYUP_ARROW_DOWN"

    KEYBOARD_KEYDOWN_ARROW_RIGHT  = "BUILTIN_KEYBOARD_KEYDOWN_ARROW_RIGHT"
    KEYBOARD_KEYUP_ARROW_RIGHT  = "BUILTIN_KEYBOARD_KEYUP_ARROW_RIGHT"