

class LogConfig:
    DEBUG_PRINT_LOG_UDPATES = True
    DEBUG_PRINT_UNSUCCESFUL_EVENTS = True
    DEBUG_PRINT_AURA_TICKS = True
    DEBUG_PRINT_AURA_UPDATES = True
    DEBUG_PRINT_GAME_OBJ_UPDATES = True
    DEBUG_PRINT_GAME_OBJ_POSITIONAL_UPDATES = False